// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuestBooking.Infrastructure;

#nullable disable

namespace QuestBooking.Infrastructure.Migrations
{
    [DbContext(typeof(QuestBookingIcptContext))]
    partial class QuestBookingIcptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bookingservice", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.HasKey("BookingId", "ServiceId")
                        .HasName("bookingservices_pkey");

                    b.HasIndex("ServiceId");

                    b.ToTable("bookingservices", (string)null);
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("PromocodeId")
                        .HasColumnType("integer")
                        .HasColumnName("promocode_id");

                    b.Property<int>("SlotId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_price");

                    b.HasKey("Id")
                        .HasName("bookings_pkey");

                    b.HasIndex("ClientId");

                    b.HasIndex(new[] { "PromocodeId" }, "bookings_promocode_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "SlotId" }, "bookings_slot_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "PromocodeId" }, "unique_promocode")
                        .IsUnique();

                    b.HasIndex(new[] { "SlotId" }, "unique_slot")
                        .IsUnique();

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("clients_pkey");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.Extraservice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("service_name");

                    b.HasKey("Id")
                        .HasName("extraservices_pkey");

                    b.ToTable("extraservices", (string)null);
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.Promocode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percent");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("promocodes_pkey");

                    b.HasIndex(new[] { "Code" }, "promocodes_code_key")
                        .IsUnique();

                    b.ToTable("promocodes", (string)null);
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.Questroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("duration_minutes");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("questrooms_pkey");

                    b.ToTable("questrooms", (string)null);
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.Timeslot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("timeslots_pkey");

                    b.HasIndex("RoomId");

                    b.ToTable("timeslots", (string)null);
                });

            modelBuilder.Entity("Bookingservice", b =>
                {
                    b.HasOne("QuestBooking.Domain.Model.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bookingservices_booking_id_fkey");

                    b.HasOne("QuestBooking.Domain.Model.Extraservice", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bookingservices_service_id_fkey");
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.Booking", b =>
                {
                    b.HasOne("QuestBooking.Domain.Model.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("bookings_client_id_fkey");

                    b.HasOne("QuestBooking.Domain.Model.Promocode", "Promocode")
                        .WithOne("Booking")
                        .HasForeignKey("QuestBooking.Domain.Model.Booking", "PromocodeId")
                        .HasConstraintName("bookings_promocode_id_fkey");

                    b.HasOne("QuestBooking.Domain.Model.Timeslot", "Slot")
                        .WithOne("Booking")
                        .HasForeignKey("QuestBooking.Domain.Model.Booking", "SlotId")
                        .IsRequired()
                        .HasConstraintName("bookings_slot_id_fkey");

                    b.Navigation("Client");

                    b.Navigation("Promocode");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.Timeslot", b =>
                {
                    b.HasOne("QuestBooking.Domain.Model.Questroom", "Room")
                        .WithMany("Timeslots")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("timeslots_room_id_fkey");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.Client", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.Promocode", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.Questroom", b =>
                {
                    b.Navigation("Timeslots");
                });

            modelBuilder.Entity("QuestBooking.Domain.Model.Timeslot", b =>
                {
                    b.Navigation("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
